# This is a basic workflow that is manually triggered

name: Manual workflow2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      regionFlag:
        description: 'regionFlag'
        required: true
        type: choice
        options:
        - US
        - EU

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  print-location:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - id: confirm_regionFlag
        run: echo "Hello, USA"
      - name: |
        #if [[ ${{ steps.confirm_regionFlag.outputs.regionFlag }} == 'EU' ]]; then exit 'flag_err'; else exit 'US'; fi
        #if [[ ${{ github.event.inputs.regionFlag }} == 'EU' ]]; then exit 'flagErr'; else exit 'US'; fi
        if regionFlag == US
