name: regional_dispatch_template

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: true
        default: US
        description: US or EU?
      productionLabel:
        type: string
        required: true
        default: true
        description: true for production runs or false for non-production
      apkPath:
        type: string
        required: false
        default: false
        description: apkPatch description goes here
      testerGroup:
        type: string
        required: false
        default: false
        description: testerGroup description goes here
      releaseNotes:
        type: string
        required: false
        default: false
        description: releaseNotes description goes here
      packageName:
        type: string
        required: false
        default: false
        description: packageName description goes here
      releaseFile:
        type: string
        required: false
        default: false
        description: releaseFile description goes here
      releaseTrack:
        type: string
        required: true
        default: false
        description: releaseTrack description goes here

jobs:
  us:
    if: ${{ inputs.region == 'US' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #actions/checkout@v2 #Need to add git-checkout function
      - run: .github/workflows/bash.sh US #$GITHUB_REF
  eu:
    if: ${{ inputs.region == 'EU' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # actions/checkout@v2 - Need to add git-checkout function
      - run: .github/workflows/bash.sh EU #$GITHUB_REF
  bad-country-input:
    if: ${{ inputs.region != 'US' && inputs.region != 'EU' }}
    runs-on: ubuntu-latest
    steps:
      # Need to add git-checkout function
      - run: echo 'input.region invalid; choose from US or EU' && exit 1
  # production:
    # if: ${{ GITHUB_REF == 'ref/heads/production' }}
    # runs-on: ubuntu-latest
    # steps:
      # - run: echo "I'm in prod"
