name: regional_dispatch

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: true
        description: US or EU?
jobs:
  us:
    if: ${{ inputs.region == 'US' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 #adds git-checkout function

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - run: echo 'fuck yeah 'US' # .github/workflows/bash.sh US #$GITHUB_REF
  eu:
    if: ${{ inputs.region == 'EU' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 #adds git-checkout function
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: echo 'fuck yeah EU' #.github/workflows/bash.sh EU #$GITHUB_REF
  bad-country-input:
    if: ${{ inputs.region != 'US'&& inputs.region != 'EU' }}
    steps:
      - run: echo 'input.region invalid; choose from US or EU' && exit 1
  # production:
    # if: ${{ GITHUB_REF == 'ref/heads/production' }}
    # runs-on: ubuntu-latest
    # steps:
      # - run: echo "I'm in prod"