name: RegionFlag_Dispatch

on:
  workflow_dispatch:
    inputs:
      regionFlag:
        type: string
        required: true
        description: US or EU?
jobs:
  us:
    if: ${{ inputs.regionFlag == 'US' }}
    runs-on: ubuntu-latest
    steps:
      # Need to add git-checkout function
      - run: ./github/workflows/bash.sh US #$GITHUB_REF
  eu:
    if: ${{ inputs.regionFlag == 'EU' }}
    runs-on: ubuntu-latest
    steps:
          # Need to add git-checkout function
      - run: ./github/workflows/bash.sh EU #$GITHUB_REF
  bad-country-input:
    if: ${{ inputs.regionFlag != 'US' && inputs.region != 'EU' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'input.regionFlag invalid; choose from US or EU' && exit 1
  # production:
    # if: ${{ GITHUB_REF == 'ref/heads/production' }}
    # runs-on: ubuntu-latest
    # steps:
      # - run: echo "I'm in prod"